export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_SHOW_MODAL = 'UPDATE_SHOW_MODAL';
export const UPDATE_SHOW_ADDPRODUCTS_MODAL = 'UPDATE_SHOW_ADDPRODUCTS_MODAL';
